# Generated by Django 4.2.2 on 2023-07-12 22:11

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="menu_items.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
                (
                    "period_time_service",
                    models.DurationField(default=datetime.timedelta(seconds=300)),
                ),
                (
                    "estimated_cooking_time",
                    models.DurationField(default=datetime.timedelta(seconds=300)),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="images/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menuItems",
                        to="menu_items.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "MenuItems",
            },
        ),
    ]
