# Generated by Django 4.2.2 on 2023-06-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.CharField(default=" ", max_length=300),
            preserve_default=False,
        ),
    ]
