# Generated by Django 4.2.2 on 2023-07-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_items", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="name",
            new_name="title",
        ),
    ]
