# Generated by Django 4.2.2 on 2023-07-01 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcontent",
            options={"ordering": ("-updated_at", "-created_at")},
        ),
        migrations.AlterModelOptions(
            name="restaurantinfo",
            options={"ordering": ("-updated_at", "-created_at")},
        ),
        migrations.AlterModelOptions(
            name="slidercontent",
            options={"ordering": ("-updated_at", "-created_at")},
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="restaurantinfo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurantinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="slidercontent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slidercontent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
