# Generated by Django 4.2.2 on 2023-07-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_slidercontent_button_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slidercontent",
            options={"ordering": ("number",)},
        ),
        migrations.AddField(
            model_name="slidercontent",
            name="number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
