# Generated by Django 4.2.2 on 2023-07-01 21:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_session", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="birthday",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 7, 2)
                    ),
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1923, 7, 2)
                    ),
                ],
            ),
        ),
    ]
