# Generated by Django 4.2.2 on 2023-06-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_session", "__first__"),
        ("menu_items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "modelinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orders.modelinfo",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[("C", "COME TO TAKE"), ("S", "SEND"), ("E", "EAT")],
                        max_length=1,
                    ),
                ),
                ("start_reserve_date", models.DateTimeField(blank=True, null=True)),
                ("end_reserve_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Orders",
            },
            bases=("orders.modelinfo",),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "modelinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orders.modelinfo",
                    ),
                ),
                ("number", models.IntegerField()),
                ("space_position", models.CharField(max_length=250)),
                ("capacity", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Tables",
            },
            bases=("orders.modelinfo",),
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "modelinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orders.modelinfo",
                    ),
                ),
                ("total_price", models.IntegerField()),
                ("final_price", models.IntegerField()),
                (
                    "related_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipt",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Receipts",
            },
            bases=("orders.modelinfo",),
        ),
        migrations.CreateModel(
            name="Order_menuItem",
            fields=[
                (
                    "modelinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orders.modelinfo",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="menu_items.menuitem",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menuItems",
                        to="orders.order",
                    ),
                ),
            ],
            bases=("orders.modelinfo",),
        ),
        migrations.AddField(
            model_name="order",
            name="table_ordered",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.table",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="user_session.usersession",
            ),
        ),
    ]
