# Generated by Django 4.2.2 on 2023-07-06 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.RegexValidator(
                        message="invalid phone number",
                        regex="^(\\+?|0*)(98)?9[\\d-]{9,}$",
                    )
                ]
            ),
        ),
    ]
