# Generated by Django 4.2.2 on 2023-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.IntegerField(
                choices=[(1, "Come to take 🚶\u200d♂️"), (2, "Send 🚚"), (3, "Eat 🍽️")]
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="serving_status",
            field=models.IntegerField(
                choices=[
                    (1, "CANCEL ❌"),
                    (2, "COOKING 🍔"),
                    (3, "POSTPONE 🔁"),
                    (4, "SERVED 🤤"),
                ]
            ),
        ),
    ]
