# Generated by Django 4.2.2 on 2023-07-06 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_table_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="invalid phone number",
                        regex="^(\\+?|0*)(98)?9[\\d-]{9,}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.IntegerField(),
        ),
    ]
