# Generated by Django 4.2.2 on 2023-07-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_phone_number_alter_table_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.table",
            ),
        ),
    ]
