# Generated by Django 4.2.2 on 2023-07-09 08:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_end_reserve_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="end_reserve_date",
        ),
        migrations.RemoveField(
            model_name="table",
            name="start_reserve_date",
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="invalid phone number",
                                regex="^(\\+?|0*)(98)?9[\\d-]{9,}$",
                            )
                        ],
                    ),
                ),
                ("start_reserve_date", models.DateTimeField()),
                ("end_reserve_date", models.DateTimeField()),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reserves",
                        to="orders.table",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
                "abstract": False,
            },
        ),
    ]
