# Generated by Django 4.2.2 on 2023-07-09 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_table_end_reserve_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserve",
            name="end_reserve_date",
        ),
        migrations.RemoveField(
            model_name="reserve",
            name="start_reserve_date",
        ),
        migrations.AddField(
            model_name="reserve",
            name="end_reserve_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reserve",
            name="reserve_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reserve",
            name="start_reserve_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
